debug: true
web_notifier:
  port: "8080"
postgres:
  host: "postgres"
  port: "5432"
  username: "dev"
  dbname: "test"
  sslmode: "disable"
redis:
  addr: "redis:6379"
  db: 0
rabbit:
  username: "admin"
  password: "password"
  host: "rabbitmq:5672"
  queue: "notifications_queue"
  exchanger: "notification_delayed"
  routing_key: "delayed_routing_key"

sender:
  email_username: "ulyanovdan28@gmail.com"
