FROM golang:1.24-alpine AS builder


WORKDIR /app

# Копируем файлы зависимостей и скачиваем их
COPY ./go.mod ./go.sum ./
RUN go mod download

# Копируем исходный код
COPY . .

# Собираем приложение
RUN CGO_ENABLED=0 GOOS=linux go build cmd/sender/main.go

# Финальный образ
FROM alpine:latest

# Добавляем пользователя для безопасности :cite[4]
RUN adduser -D -g '' appuser
USER appuser

WORKDIR /app

# Копируем собранный бинарник
COPY --from=builder /app/main .

CMD ["./main"]